#!/bin/bash

cd ..

mkdir Bpp

cd Bpp


if [ ! -d bpp-core ]; then
  #git clone https://github.com/bioPP/bpp-core
  git clone https://github.com/richelbilderbeek/bpp-core
fi

if [ ! -d bpp-seq ]; then
  #git clone https://github.com/bioPP/bpp-seq
  git clone https://github.com/richelbilderbeek/bpp-seq
fi

if [ ! -d bpp-core ]; then
  #git clone https://github.com/bioPP/bpp-core
  git clone https://github.com/richelbilderbeek/bpp-pyl
fi
